M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date Mo 14 Nov 2022 20:46:33 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-14T20:46:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.7451Y-3.6425
X3.1389Y-3.6425
T2
X2.6849Y-1.886
X2.9407Y-2.8073
X3.1995Y-1.886
T0
M30
