M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date Mo 14 Nov 2022 20:45:10 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-14T20:45:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.8031Y-5.0755
X4.1969Y-5.0755
T2
X3.7744Y-2.8988
X3.9995Y-4.14
X4.2256Y-2.8988
T0
M30
